root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/mes-lite"
  cmd = "go build -o ./tmp/mes-lite ./cmd/server"
  delay = 1000
  exclude_dir = ["tmp", "vendor", "bin"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = [".*_test.go"]

[log]
  main_only = true

[misc]
  clean_on_exit = true
