// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package reportingdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const dailyProduction = `-- name: DailyProduction :many
SELECT
    date_trunc('day', occurred_at AT TIME ZONE 'UTC')::timestamptz AS day,
    product_sku,
    sum(quantity)::bigint AS total_quantity,
    count(*)::bigint AS entry_count
FROM production_entries
WHERE occurred_at >= $1
  AND occurred_at < $2
GROUP BY day, product_sku
ORDER BY day ASC, product_sku ASC
`

type DailyProductionParams struct {
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
}

type DailyProductionRow struct {
	Day           pgtype.Timestamptz `json:"day"`
	ProductSku    string             `json:"product_sku"`
	TotalQuantity int64              `json:"total_quantity"`
	EntryCount    int64              `json:"entry_count"`
}

func (q *Queries) DailyProduction(ctx context.Context, arg DailyProductionParams) ([]DailyProductionRow, error) {
	rows, err := q.db.Query(ctx, dailyProduction, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyProductionRow{}
	for rows.Next() {
		var i DailyProductionRow
		if err := rows.Scan(
			&i.Day,
			&i.ProductSku,
			&i.TotalQuantity,
			&i.EntryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const employeeProductivity = `-- name: EmployeeProductivity :many
SELECT
    pe.employee_id,
    e.first_name,
    e.last_name,
    sum(pe.quantity)::bigint AS total_quantity,
    count(*)::bigint AS entry_count
FROM production_entries pe
JOIN employees e ON e.id = pe.employee_id
WHERE pe.occurred_at >= $1
  AND pe.occurred_at < $2
GROUP BY pe.employee_id, e.first_name, e.last_name
ORDER BY total_quantity DESC, entry_count DESC, pe.employee_id ASC
`

type EmployeeProductivityParams struct {
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
}

type EmployeeProductivityRow struct {
	EmployeeID    string `json:"employee_id"`
	FirstName     string `json:"first_name"`
	LastName      string `json:"last_name"`
	TotalQuantity int64  `json:"total_quantity"`
	EntryCount    int64  `json:"entry_count"`
}

func (q *Queries) EmployeeProductivity(ctx context.Context, arg EmployeeProductivityParams) ([]EmployeeProductivityRow, error) {
	rows, err := q.db.Query(ctx, employeeProductivity, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmployeeProductivityRow{}
	for rows.Next() {
		var i EmployeeProductivityRow
		if err := rows.Scan(
			&i.EmployeeID,
			&i.FirstName,
			&i.LastName,
			&i.TotalQuantity,
			&i.EntryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
