// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package reportingdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const dailyProduction = `-- name: DailyProduction :many
SELECT
    date_trunc('day', occurred_at AT TIME ZONE 'UTC')::timestamptz AS day,
    product_sku,
    sum(quantity)::bigint AS total_quantity,
    count(*)::bigint AS entry_count
FROM production_entries
WHERE occurred_at >= $1
  AND occurred_at < $2
GROUP BY day, product_sku
ORDER BY day ASC, product_sku ASC
`

type DailyProductionParams struct {
	FromTime pgtype.Timestamptz `json:"from_time"`
	ToTime   pgtype.Timestamptz `json:"to_time"`
}

type DailyProductionRow struct {
	Day           pgtype.Timestamptz `json:"day"`
	ProductSku    string             `json:"product_sku"`
	TotalQuantity int64              `json:"total_quantity"`
	EntryCount    int64              `json:"entry_count"`
}

func (q *Queries) DailyProduction(ctx context.Context, arg DailyProductionParams) ([]DailyProductionRow, error) {
	rows, err := q.db.Query(ctx, dailyProduction, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyProductionRow{}
	for rows.Next() {
		var i DailyProductionRow
		if err := rows.Scan(
			&i.Day,
			&i.ProductSku,
			&i.TotalQuantity,
			&i.EntryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
