// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package productsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    sku,
    name,
    category,
    unit,
    is_active,
    version
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING sku, name, category, unit, is_active, version, created_at, updated_at
`

type CreateProductParams struct {
	Sku      string `json:"sku"`
	Name     string `json:"name"`
	Category int32  `json:"category"`
	Unit     string `json:"unit"`
	IsActive bool   `json:"is_active"`
	Version  int32  `json:"version"`
}

type CreateProductRow struct {
	Sku       string             `json:"sku"`
	Name      string             `json:"name"`
	Category  int32              `json:"category"`
	Unit      string             `json:"unit"`
	IsActive  bool               `json:"is_active"`
	Version   int32              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Sku,
		arg.Name,
		arg.Category,
		arg.Unit,
		arg.IsActive,
		arg.Version,
	)
	var i CreateProductRow
	err := row.Scan(
		&i.Sku,
		&i.Name,
		&i.Category,
		&i.Unit,
		&i.IsActive,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT sku, name, category, unit, is_active, version, created_at, updated_at
FROM products
WHERE sku = $1
`

type GetProductRow struct {
	Sku       string             `json:"sku"`
	Name      string             `json:"name"`
	Category  int32              `json:"category"`
	Unit      string             `json:"unit"`
	IsActive  bool               `json:"is_active"`
	Version   int32              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetProduct(ctx context.Context, sku string) (GetProductRow, error) {
	row := q.db.QueryRow(ctx, getProduct, sku)
	var i GetProductRow
	err := row.Scan(
		&i.Sku,
		&i.Name,
		&i.Category,
		&i.Unit,
		&i.IsActive,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT sku, name, category, unit, is_active, version, created_at, updated_at
FROM products
WHERE ($1::text = ''
    OR lower(sku) LIKE '%' || lower($1::text) || '%'
    OR lower(name) LIKE '%' || lower($1::text) || '%'
    OR lower(CASE category
        WHEN 0 THEN 'Ventilation'
        WHEN 1 THEN 'Filter'
        WHEN 2 THEN 'Duct'
        WHEN 3 THEN 'Mounting'
        WHEN 4 THEN 'Other'
        ELSE 'Unknown'
    END) LIKE '%' || lower($1::text) || '%')
  AND ($2::text = '' OR is_active = ($2::text = 'true'))
ORDER BY
    CASE WHEN $3::text = 'sku' THEN sku END ASC,
    CASE WHEN $3::text = '-sku' THEN sku END DESC,
    CASE WHEN $3::text = 'name' THEN name END ASC,
    CASE WHEN $3::text = '-name' THEN name END DESC,
    CASE WHEN $3::text = 'category' THEN category END ASC,
    CASE WHEN $3::text = '-category' THEN category END DESC,
    sku ASC
LIMIT $5 OFFSET $4
`

type ListProductsParams struct {
	Query       string `json:"query"`
	Active      string `json:"active"`
	Sort        string `json:"sort"`
	OffsetValue int32  `json:"offset_value"`
	LimitValue  int32  `json:"limit_value"`
}

type ListProductsRow struct {
	Sku       string             `json:"sku"`
	Name      string             `json:"name"`
	Category  int32              `json:"category"`
	Unit      string             `json:"unit"`
	IsActive  bool               `json:"is_active"`
	Version   int32              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.Query,
		arg.Active,
		arg.Sort,
		arg.OffsetValue,
		arg.LimitValue,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsRow{}
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.Sku,
			&i.Name,
			&i.Category,
			&i.Unit,
			&i.IsActive,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $2,
    category = $3,
    unit = $4,
    is_active = $5,
    version = version + 1,
    updated_at = now()
WHERE sku = $1 AND version = $6
RETURNING sku, name, category, unit, is_active, version, created_at, updated_at
`

type UpdateProductParams struct {
	Sku      string `json:"sku"`
	Name     string `json:"name"`
	Category int32  `json:"category"`
	Unit     string `json:"unit"`
	IsActive bool   `json:"is_active"`
	Version  int32  `json:"version"`
}

type UpdateProductRow struct {
	Sku       string             `json:"sku"`
	Name      string             `json:"name"`
	Category  int32              `json:"category"`
	Unit      string             `json:"unit"`
	IsActive  bool               `json:"is_active"`
	Version   int32              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (UpdateProductRow, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Sku,
		arg.Name,
		arg.Category,
		arg.Unit,
		arg.IsActive,
		arg.Version,
	)
	var i UpdateProductRow
	err := row.Scan(
		&i.Sku,
		&i.Name,
		&i.Category,
		&i.Unit,
		&i.IsActive,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
