// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package ordersdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO production_orders (
    id,
    status,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4
) RETURNING id, status, created_at, updated_at
`

type CreateOrderParams struct {
	ID        string             `json:"id"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (ProductionOrder, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ProductionOrder
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderAssignment = `-- name: CreateOrderAssignment :exec
INSERT INTO production_order_assignments (
    order_id,
    employee_id
) VALUES (
    $1, $2
)
`

type CreateOrderAssignmentParams struct {
	OrderID    string `json:"order_id"`
	EmployeeID string `json:"employee_id"`
}

func (q *Queries) CreateOrderAssignment(ctx context.Context, arg CreateOrderAssignmentParams) error {
	_, err := q.db.Exec(ctx, createOrderAssignment, arg.OrderID, arg.EmployeeID)
	return err
}

const createOrderLine = `-- name: CreateOrderLine :exec
INSERT INTO production_order_lines (
    order_id,
    product_sku,
    planned_quantity
) VALUES (
    $1, $2, $3
)
`

type CreateOrderLineParams struct {
	OrderID         string `json:"order_id"`
	ProductSku      string `json:"product_sku"`
	PlannedQuantity int32  `json:"planned_quantity"`
}

func (q *Queries) CreateOrderLine(ctx context.Context, arg CreateOrderLineParams) error {
	_, err := q.db.Exec(ctx, createOrderLine, arg.OrderID, arg.ProductSku, arg.PlannedQuantity)
	return err
}

const deleteOrderAssignments = `-- name: DeleteOrderAssignments :exec
DELETE FROM production_order_assignments
WHERE order_id = $1
`

func (q *Queries) DeleteOrderAssignments(ctx context.Context, orderID string) error {
	_, err := q.db.Exec(ctx, deleteOrderAssignments, orderID)
	return err
}

const getOrder = `-- name: GetOrder :one
SELECT id, status, created_at, updated_at
FROM production_orders
WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id string) (ProductionOrder, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i ProductionOrder
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrderAssignments = `-- name: ListOrderAssignments :many
SELECT order_id, employee_id
FROM production_order_assignments
WHERE order_id = $1
ORDER BY employee_id ASC
`

func (q *Queries) ListOrderAssignments(ctx context.Context, orderID string) ([]ProductionOrderAssignment, error) {
	rows, err := q.db.Query(ctx, listOrderAssignments, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductionOrderAssignment{}
	for rows.Next() {
		var i ProductionOrderAssignment
		if err := rows.Scan(&i.OrderID, &i.EmployeeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderLines = `-- name: ListOrderLines :many
SELECT order_id, product_sku, planned_quantity
FROM production_order_lines
WHERE order_id = $1
ORDER BY product_sku ASC
`

func (q *Queries) ListOrderLines(ctx context.Context, orderID string) ([]ProductionOrderLine, error) {
	rows, err := q.db.Query(ctx, listOrderLines, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductionOrderLine{}
	for rows.Next() {
		var i ProductionOrderLine
		if err := rows.Scan(&i.OrderID, &i.ProductSku, &i.PlannedQuantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrder = `-- name: UpdateOrder :one
UPDATE production_orders
SET status = $2,
    updated_at = $3
WHERE id = $1
RETURNING id, status, created_at, updated_at
`

type UpdateOrderParams struct {
	ID        string             `json:"id"`
	Status    string             `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (ProductionOrder, error) {
	row := q.db.QueryRow(ctx, updateOrder, arg.ID, arg.Status, arg.UpdatedAt)
	var i ProductionOrder
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
