// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: employees.sql

package employeesdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (
    id,
    first_name,
    last_name,
    email,
    is_active,
    version
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, first_name, last_name, email, is_active, version, created_at, updated_at
`

type CreateEmployeeParams struct {
	ID        string `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
	IsActive  bool   `json:"is_active"`
	Version   int32  `json:"version"`
}

type CreateEmployeeRow struct {
	ID        string             `json:"id"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	Email     string             `json:"email"`
	IsActive  bool               `json:"is_active"`
	Version   int32              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (CreateEmployeeRow, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.IsActive,
		arg.Version,
	)
	var i CreateEmployeeRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.IsActive,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployee = `-- name: GetEmployee :one
SELECT id, first_name, last_name, email, is_active, version, created_at, updated_at
FROM employees
WHERE id = $1
`

type GetEmployeeRow struct {
	ID        string             `json:"id"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	Email     string             `json:"email"`
	IsActive  bool               `json:"is_active"`
	Version   int32              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetEmployee(ctx context.Context, id string) (GetEmployeeRow, error) {
	row := q.db.QueryRow(ctx, getEmployee, id)
	var i GetEmployeeRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.IsActive,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEmployees = `-- name: ListEmployees :many
SELECT id, first_name, last_name, email, is_active, version, created_at, updated_at
FROM employees
WHERE ($1::text = ''
    OR lower(id) LIKE '%' || lower($1::text) || '%'
    OR lower(first_name) LIKE '%' || lower($1::text) || '%'
    OR lower(last_name) LIKE '%' || lower($1::text) || '%'
    OR lower(email) LIKE '%' || lower($1::text) || '%')
  AND ($2::text = '' OR is_active = ($2::text = 'true'))
ORDER BY
    CASE WHEN $3::text = 'id' THEN id END ASC,
    CASE WHEN $3::text = '-id' THEN id END DESC,
    CASE WHEN $3::text = 'name' THEN last_name END ASC,
    CASE WHEN $3::text = 'name' THEN first_name END ASC,
    CASE WHEN $3::text = '-name' THEN last_name END DESC,
    CASE WHEN $3::text = '-name' THEN first_name END DESC,
    CASE WHEN $3::text = 'email' THEN email END ASC,
    CASE WHEN $3::text = '-email' THEN email END DESC,
    id ASC
LIMIT $5 OFFSET $4
`

type ListEmployeesParams struct {
	Query       string `json:"query"`
	Active      string `json:"active"`
	Sort        string `json:"sort"`
	OffsetValue int32  `json:"offset_value"`
	LimitValue  int32  `json:"limit_value"`
}

type ListEmployeesRow struct {
	ID        string             `json:"id"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	Email     string             `json:"email"`
	IsActive  bool               `json:"is_active"`
	Version   int32              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]ListEmployeesRow, error) {
	rows, err := q.db.Query(ctx, listEmployees,
		arg.Query,
		arg.Active,
		arg.Sort,
		arg.OffsetValue,
		arg.LimitValue,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeesRow{}
	for rows.Next() {
		var i ListEmployeesRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.IsActive,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE employees
SET first_name = $2,
    last_name = $3,
    email = $4,
    is_active = $5,
    version = version + 1,
    updated_at = now()
WHERE id = $1 AND version = $6
RETURNING id, first_name, last_name, email, is_active, version, created_at, updated_at
`

type UpdateEmployeeParams struct {
	ID        string `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
	IsActive  bool   `json:"is_active"`
	Version   int32  `json:"version"`
}

type UpdateEmployeeRow struct {
	ID        string             `json:"id"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	Email     string             `json:"email"`
	IsActive  bool               `json:"is_active"`
	Version   int32              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (UpdateEmployeeRow, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.IsActive,
		arg.Version,
	)
	var i UpdateEmployeeRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.IsActive,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
