// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package employeesdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthUser struct {
	ID           string             `json:"id"`
	Email        string             `json:"email"`
	PasswordHash []byte             `json:"password_hash"`
	Role         string             `json:"role"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Employee struct {
	ID        string             `json:"id"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
	Email     string             `json:"email"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Version   int32              `json:"version"`
}

type Product struct {
	Sku       string             `json:"sku"`
	Name      string             `json:"name"`
	Category  int32              `json:"category"`
	Unit      string             `json:"unit"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Version   int32              `json:"version"`
}

type ProductionEntry struct {
	ID          pgtype.UUID        `json:"id"`
	EmployeeID  string             `json:"employee_id"`
	ProductSku  string             `json:"product_sku"`
	Quantity    int32              `json:"quantity"`
	Workstation string             `json:"workstation"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	Comment     string             `json:"comment"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	RequestID   string             `json:"request_id"`
}

type ProductionEntryCorrection struct {
	ID          pgtype.UUID        `json:"id"`
	EntryID     pgtype.UUID        `json:"entry_id"`
	ActorUserID string             `json:"actor_user_id"`
	Reason      string             `json:"reason"`
	EmployeeID  string             `json:"employee_id"`
	ProductSku  string             `json:"product_sku"`
	Quantity    int32              `json:"quantity"`
	Workstation string             `json:"workstation"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	Comment     string             `json:"comment"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ProductionOrder struct {
	ID        string             `json:"id"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Version   int32              `json:"version"`
}

type ProductionOrderAssignment struct {
	OrderID    string `json:"order_id"`
	EmployeeID string `json:"employee_id"`
}

type ProductionOrderLine struct {
	OrderID         string `json:"order_id"`
	ProductSku      string `json:"product_sku"`
	PlannedQuantity int32  `json:"planned_quantity"`
}
