// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package authdb

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO auth_users (
    id,
    email,
    password_hash,
    role,
    is_active
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, email, password_hash, role, is_active, created_at, updated_at
`

type CreateUserParams struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	PasswordHash []byte `json:"password_hash"`
	Role         string `json:"role"`
	IsActive     bool   `json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.IsActive,
	)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, is_active, created_at, updated_at
FROM auth_users
WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userExistsByEmail = `-- name: UserExistsByEmail :one
SELECT EXISTS(
    SELECT 1
    FROM auth_users
    WHERE lower(email) = lower($1)
)
`

func (q *Queries) UserExistsByEmail(ctx context.Context, lower string) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsByEmail, lower)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
