// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package productiondb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCorrection = `-- name: CreateCorrection :one
INSERT INTO production_entry_corrections (
    id,
    entry_id,
    actor_user_id,
    reason,
    employee_id,
    product_sku,
    quantity,
    workstation,
    occurred_at,
    comment,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, entry_id, actor_user_id, reason, employee_id, product_sku, quantity, workstation, occurred_at, comment, created_at
`

type CreateCorrectionParams struct {
	ID          pgtype.UUID        `json:"id"`
	EntryID     pgtype.UUID        `json:"entry_id"`
	ActorUserID string             `json:"actor_user_id"`
	Reason      string             `json:"reason"`
	EmployeeID  string             `json:"employee_id"`
	ProductSku  string             `json:"product_sku"`
	Quantity    int32              `json:"quantity"`
	Workstation string             `json:"workstation"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	Comment     string             `json:"comment"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateCorrection(ctx context.Context, arg CreateCorrectionParams) (ProductionEntryCorrection, error) {
	row := q.db.QueryRow(ctx, createCorrection,
		arg.ID,
		arg.EntryID,
		arg.ActorUserID,
		arg.Reason,
		arg.EmployeeID,
		arg.ProductSku,
		arg.Quantity,
		arg.Workstation,
		arg.OccurredAt,
		arg.Comment,
		arg.CreatedAt,
	)
	var i ProductionEntryCorrection
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.ActorUserID,
		&i.Reason,
		&i.EmployeeID,
		&i.ProductSku,
		&i.Quantity,
		&i.Workstation,
		&i.OccurredAt,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const createEntry = `-- name: CreateEntry :one
INSERT INTO production_entries (
    id,
    request_id,
    employee_id,
    product_sku,
    quantity,
    workstation,
    occurred_at,
    comment
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, employee_id, product_sku, quantity, workstation, occurred_at, comment, created_at, request_id
`

type CreateEntryParams struct {
	ID          pgtype.UUID        `json:"id"`
	RequestID   string             `json:"request_id"`
	EmployeeID  string             `json:"employee_id"`
	ProductSku  string             `json:"product_sku"`
	Quantity    int32              `json:"quantity"`
	Workstation string             `json:"workstation"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	Comment     string             `json:"comment"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (ProductionEntry, error) {
	row := q.db.QueryRow(ctx, createEntry,
		arg.ID,
		arg.RequestID,
		arg.EmployeeID,
		arg.ProductSku,
		arg.Quantity,
		arg.Workstation,
		arg.OccurredAt,
		arg.Comment,
	)
	var i ProductionEntry
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.ProductSku,
		&i.Quantity,
		&i.Workstation,
		&i.OccurredAt,
		&i.Comment,
		&i.CreatedAt,
		&i.RequestID,
	)
	return i, err
}

const getEntry = `-- name: GetEntry :one
SELECT id, employee_id, product_sku, quantity, workstation, occurred_at, comment, created_at, request_id
FROM production_entries
WHERE id = $1
`

func (q *Queries) GetEntry(ctx context.Context, id pgtype.UUID) (ProductionEntry, error) {
	row := q.db.QueryRow(ctx, getEntry, id)
	var i ProductionEntry
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.ProductSku,
		&i.Quantity,
		&i.Workstation,
		&i.OccurredAt,
		&i.Comment,
		&i.CreatedAt,
		&i.RequestID,
	)
	return i, err
}

const getEntryByRequestID = `-- name: GetEntryByRequestID :one
SELECT id, employee_id, product_sku, quantity, workstation, occurred_at, comment, created_at, request_id
FROM production_entries
WHERE request_id = $1
`

func (q *Queries) GetEntryByRequestID(ctx context.Context, requestID string) (ProductionEntry, error) {
	row := q.db.QueryRow(ctx, getEntryByRequestID, requestID)
	var i ProductionEntry
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.ProductSku,
		&i.Quantity,
		&i.Workstation,
		&i.OccurredAt,
		&i.Comment,
		&i.CreatedAt,
		&i.RequestID,
	)
	return i, err
}

const listCorrections = `-- name: ListCorrections :many
SELECT id, entry_id, actor_user_id, reason, employee_id, product_sku, quantity, workstation, occurred_at, comment, created_at
FROM production_entry_corrections
WHERE entry_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListCorrections(ctx context.Context, entryID pgtype.UUID) ([]ProductionEntryCorrection, error) {
	rows, err := q.db.Query(ctx, listCorrections, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductionEntryCorrection{}
	for rows.Next() {
		var i ProductionEntryCorrection
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.ActorUserID,
			&i.Reason,
			&i.EmployeeID,
			&i.ProductSku,
			&i.Quantity,
			&i.Workstation,
			&i.OccurredAt,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntries = `-- name: ListEntries :many
SELECT id, employee_id, product_sku, quantity, workstation, occurred_at, comment, created_at, request_id
FROM production_entries
WHERE ($1::text = '' OR employee_id = $1::text)
  AND ($2::text = '' OR product_sku = $2::text)
  AND ($3::text = '' OR lower(workstation) LIKE '%' || lower($3::text) || '%')
  AND (NOT $4::boolean OR occurred_at >= $5)
  AND (NOT $6::boolean OR occurred_at < $7)
ORDER BY occurred_at DESC, created_at DESC, id DESC
LIMIT $9 OFFSET $8
`

type ListEntriesParams struct {
	EmployeeID  string             `json:"employee_id"`
	ProductSku  string             `json:"product_sku"`
	Workstation string             `json:"workstation"`
	FromTime    bool               `json:"from_time"`
	FromValue   pgtype.Timestamptz `json:"from_value"`
	ToTime      bool               `json:"to_time"`
	ToValue     pgtype.Timestamptz `json:"to_value"`
	OffsetValue int32              `json:"offset_value"`
	LimitValue  int32              `json:"limit_value"`
}

func (q *Queries) ListEntries(ctx context.Context, arg ListEntriesParams) ([]ProductionEntry, error) {
	rows, err := q.db.Query(ctx, listEntries,
		arg.EmployeeID,
		arg.ProductSku,
		arg.Workstation,
		arg.FromTime,
		arg.FromValue,
		arg.ToTime,
		arg.ToValue,
		arg.OffsetValue,
		arg.LimitValue,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductionEntry{}
	for rows.Next() {
		var i ProductionEntry
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.ProductSku,
			&i.Quantity,
			&i.Workstation,
			&i.OccurredAt,
			&i.Comment,
			&i.CreatedAt,
			&i.RequestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
