// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package productiondb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ProductionEntry struct {
	ID          pgtype.UUID        `json:"id"`
	EmployeeID  string             `json:"employee_id"`
	ProductSku  string             `json:"product_sku"`
	Quantity    int32              `json:"quantity"`
	Workstation string             `json:"workstation"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	Comment     string             `json:"comment"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
